<a href="https://colab.research.google.com/github/hemanjalireddy/Polynomial_regression/blob/main/Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Polynomial Regression

## Import the libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

## Load the data

In [3]:
data = pd.read_csv('/content/Position_Salaries.csv')
x = data.iloc[ : , 1:-1].values
y = data.iloc[: , -1].values

In [6]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [5]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

## Train the Linear Regression model on the whole dataset



In [7]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(x,y)


LinearRegression()

In [13]:
print(linear_reg.score(x,y))
intercept = linear_reg.intercept_
coef = linear_reg.coef_

0.6690412331929895


In [16]:
y_hat1 = intercept + coef*x

## Training the Polynomial Regression model on the whole dataset

In [17]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree =2)
x_poly = poly_reg.fit_transform(x)
lin_reg2 = LinearRegression()
lin_reg2.fit(x_poly,y)

LinearRegression()

In [18]:
lin_reg2.score(x_poly , y)

0.9162082221443942

In [20]:
coef2 =lin_reg2.coef_
intercept2 = lin_reg2.intercept_
print(coef2)
print(intercept2)

[      0.         -132871.21212121   19431.81818182]
232166.6666666664
